config/routes.rb
Rails.application.routes.draw do

  devise_for :end_users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions',
  }

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions",
  }

  root to: 'public/homes#top'
  get '/about' => 'public/homes#about'
  get '/rakuten_books' => 'public/rakuten_books#search'
  get "/unsubscribe/end_users/:id" => "public/end_users#unsubscribe", as: 'unsubscribe'
  get 'chat/:id' => 'public/chats#show', as: 'chat'
  get "search" => "public/searches#search"
  patch "end_users/withdraw" => "public/end_users#withdraw"
  post "contacts/new" => "public/contacts#create"
  get "/thanks" => "public/contacts#thanks"

  scope module: :public do
    patch "/end_users/withdraw" => "end_users#withdraw"
    get 'searches/search_result'
    resources :end_users, only: [:edit, :update, :index, :show] do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
    resources :reviews, except: [:index] do
      resources :comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
      collection do
        get 'sort_new'
        get 'sort_rate'
      end
    end
    resources :chats, only: [:create]
    resources :notifications, only: [:index, :destroy]
    resources :contacts, only: [:new]
  end

  namespace :admin do
    resources :genres, only: [:index, :create, :destroy]
    resources :end_users, only: [:index, :show, :edit, :update]
    root to: "homes#top"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, presence: true

  def self.extruct_reviews_from_genre(genre)
    genre.reviews
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to request.referer, notice: 'ジャンルの新規登録に成功しました。'
    else
      @genres = Genre.all
      render :index
    end
  end

  def destroy
    @genre = Genre.find(params[:id])
    if @genre.destroy
      redirect_to request.referer, notice: 'ジャンルの削除に成功しました。'
    else
      @genres = Genre.all
      render :index
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admin/genres/index.html.erb
<div class="container background-color p-5 mb-5">
  <div class="row offset-md-4">
    <h3 class="p-3">
      <span>ジャンル一覧・追加</span>
    </h3>
  </div>
  <h5 class="error_explanation">
    <%= render 'layouts/errors', obj: @genre %>
  </h5>
  <%= form_with model: @genre, url:admin_genres_path, method: :post, local: true do |f| %>
    <div class="form-group row offset-2">
      <%= f.label :ジャンル名, class:"col-12 col-md-2 col-form-label font-weight-bold ml-4" %>
        <div class="col-12 col-md-5">
          <%= f.text_field :name, autofocus: true, placeholder: "ジャンル名", class:"form-control mb-2"  %>
        </div>
        <div class="col-12 col-md-2">
          <%= f.submit '新規登録', class: "btn btn-outline-success text-dark" %>
        </div>
    </div>
  <% end %>

  <div class="row mt-5 offset-md-4">
    <div class="col-md-6">
      <table class="table">
        <tbody>
          <tr class="table-active">
            <td>ジャンル名</td>
            <td></td>
          </tr>
          <% @genres.each do |genre| %>
            <tr>
              <td><%= genre.name %></td>
              <td><%= link_to "削除する", admin_genre_path(genre), method: :delete, class: "btn btn-outline-danger text-dark" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="mx-auto">
      <%= link_to '戻る', admin_end_users_path, class: "btn btn-outline-secondary text-dark" %>
    </div>
  </div>
</div>