config/routes.rb
Rails.application.routes.draw do

  devise_for :end_users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions',
  }

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions",
  }

  root to: 'public/homes#top'
  get '/about' => 'public/homes#about'
  get '/rakuten_books' => 'public/rakuten_books#search'
  get "/unsubscribe/end_users/:id" => "public/end_users#unsubscribe", as: 'unsubscribe'
  get 'chat/:id' => 'public/chats#show', as: 'chat'
  get "search" => "public/searches#search"
  patch "end_users/withdraw" => "public/end_users#withdraw"
  post "contacts/new" => "public/contacts#create"
  get "/thanks" => "public/contacts#thanks"

  scope module: :public do
    patch "/end_users/withdraw" => "end_users#withdraw"
    get 'searches/search_result'
    resources :end_users, only: [:edit, :update, :index, :show] do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
    resources :reviews, except: [:index] do
      resources :comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
      collection do
        get 'sort_new'
        get 'sort_rate'
      end
    end
    resources :chats, only: [:create]
    resources :notifications, only: [:index, :destroy]
    resources :contacts, only: [:new]
  end

  namespace :admin do
    resources :genres, only: [:index, :create, :destroy]
    resources :end_users, only: [:index, :show, :edit, :update]
    root to: "homes#top"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/end_user.rb
class EndUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  enum gender: { man: 1, woman: 2, other: 3 }

  validates :nick_name, presence: true
  validates :gender, presence: true
  validates :occupation, presence: true
  validates :birthday, presence: true
  validates :email, presence: true

  has_many :reviews, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_reviews, through: :favorites, source: :review
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :end_user_rooms, dependent: :destroy
  has_many :chats, dependent: :destroy
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy

  has_one_attached :profile_image

  def follow(end_user_id)
    relationships.create(followed_id: end_user_id)
  end

  def unfollow(end_user_id)
    relationships.find_by(followed_id: end_user_id).destroy
  end

  def following?(end_user)
    followings.include?(end_user)
  end

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpeg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def calc_age # 生年月日から年齢を計算するメソッド
    d1 = birthday.strftime("%Y%m%d").to_i
    d2 = Date.today.strftime("%Y%m%d").to_i
    (d2 - d1) / 10000
  end

  def self.search(search, word)
    return all if word.blank?

    if search == "perfect_match"
      where("nick_name = ?", "#{word}")
    elsif search == "forward_match"
      where("nick_name LIKE?", "#{word}%")
    elsif search == "backward_match"
      where("nick_name LIKE?", "%#{word}")
    elsif search == "partial_match"
      where("nick_name LIKE?", "%#{word}%")
    else
      all
    end
  end

  def create_notification_follow!(visitor)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ? ", visitor.id, id, 'follow'])
    if temp.blank?
      notification = visitor.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end
end

app/controllers/admin/end_users_controller.rb
class Admin::EndUsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @end_users = EndUser.all
  end

  def show
    @end_user = EndUser.find(params[:id])
  end

  def edit
    @end_user = EndUser.find(params[:id])
  end

  def update
    @end_user = EndUser.find(params[:id])
    if @end_user.update(end_user_params)
      redirect_to admin_end_user_path(@end_user), notice: 'ユーザー情報の編集に成功しました。'
    else
      render :edit
    end
  end

  private

  def end_user_params
    params.require(:end_user).permit(
      :nick_name,
      :birthday,
      :gender,
      :occupation,
      :email,
      :is_deleted
    )
  end
end

app/helpers/admin/end_users_helper.rb
module Admin::EndUsersHelper
end

app/views/admin/end_users/edit.html.erb
<div class="container background-color p-5 mb-5">
  <div class="row">
    <h3 class="p-3 mx-auto"><%= @end_user.nick_name %>さんのユーザー情報編集</h3>
  </div>
  <h5 class="error_explanation">
    <%= render 'layouts/errors', obj: @end_user %>
  </h5>

  <%= form_with model: @end_user, url: admin_end_user_path(@end_user), method: :patch do |f| %>
    <form>
      <div class="form-group row">
        <%= f.label :ユーザーID, class:"col-6 col-md-2 col-form-label col-md-2 offset-md-4" %>
        <div class="col-6 mt-2 col-md-5 offset-md-1">
          <%= @end_user.id %>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :ニックネーム, class:"col-6 col-form-label col-md-2 offset-md-4" %>
          <div class="col-md-3 offset-md-1">
           <%= f.text_field :nick_name, autofocus: true, class:"form-control" %>
          </div>
      </div>

      <div class="form-group row">
        <%= f.label :性別, class:"col-sm-2 col-form-label col-md-2 offset-md-4" %>
        <div class="col-md-3 offset-md-1">
         <%= f.select :gender, EndUser.genders.keys.map {|k| [I18n.t("enums.end_user.gender.#{k}"), k]}.to_a, include_blank: "性別を選択してください" %><!--genderの中にある情報を一つずつ取り出していくイメージ-->
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :職業, class:"col-sm-2 col-form-label col-md-2 offset-md-4" %>
        <div class="col-md-3 offset-md-1">
         <%= f.select :occupation, [['会社員・会社役員'], ['自営業'], ['公務員'], ['主婦'], ['学生'], ['フリーター'], ['無職'], ['その他'] ], include_blank: "職業を選択してください" %>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :生年月日, class:"col-sm-2 col-form-label col-md-2 offset-md-4" %>
        <div class="col-md-3 offset-md-1">
         <%= f.date_select :birthday, use_month_numbers: true, start_year: 1930, end_year: (Time.now.year - 10), default: Date.new(1990, 1, 1) %>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :メールアドレス, class:"col-sm-2 col-form-label col-md-2 offset-md-4" %>
        <div class="col-md-3 offset-md-1">
         <%= f.email_field :email, autocomplete: "email", placeholder:"sample@example.com", class:"form-control" %>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :ユーザーステータス, class:"col-12 col-form-label col-md-2 offset-md-4" %>
        <div class="col-md-3 offset-md-1">
          <%= f.radio_button :is_deleted, "false"%>
          <%= f.label :is_deleted, "有効", class: "text-secondary mr-3" %>
          <%= f.radio_button :is_deleted, "true"%>
          <%= f.label :is_deleted, "退会", class: "text-secondary" %>
        </div>
      </div>

      <div class="row">
        <div class="col-12 offset-2 col-md-5 offset-md-7">
          <%= f.submit "変更を保存", class: "btn btn-outline-success text-dark" %>
          <%= link_to '戻る', admin_end_user_path(@end_user), class: "btn btn-outline-secondary text-dark offset-md-1" %>
        </div>
      </div>
    </form>
  <% end %>
</div>

app/views/admin/end_users/index.html.erb
<div class="container background-color p-5 mb-5">
  <div class="row">
    <h3 class="p-3 mx-auto"><span class="header">EndUsers</span></h3>
  </div>
  <div class="col-12 col-md-12 table-responsive">
    <table class="table table-hover">
      <thead class="table-active">
        <tr>
          <th>ユーザーID</th>
          <th>ユーザー画像</th>
          <th>ニックネーム</th>
          <th>性別</th>
          <th>年齢</th>
          <th>職業</th>
          <th>メールアドレス</th>
          <th>ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @end_users.each do |end_user| %>
          <tr>
            <td><%= end_user.id %></td>
            <td>
              <%= link_to admin_end_user_path(end_user) do %>
                <%= image_tag end_user.get_profile_image(80,80) %>
              <% end %>
            </td>
            <td><u><%=link_to end_user.nick_name, admin_end_user_path(end_user.id), class: "text-dark" %></u></td>
            <td><%= end_user.gender_i18n %></td>
            <td><%= end_user.calc_age %>歳</td>
            <td><%= end_user.occupation %></td>
            <td><%= end_user.email %></td>
            <% if end_user.is_deleted == false %>
              <td class="text-success">有効</td>
            <% else %>
              <td class="text-secondary">退会</td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/end_users/show.html.erb
<div class="container background-color p-5 mb-5">
  <div class="row">
    <h3 class="p-4 mx-auto"><%= @end_user.nick_name %>さんのユーザー情報</h3>
  </div>

  <div class="form-group row">
    <div class="col-6 col-md-2 offset-md-4">ユーザーID</div>
    <div class="col-6 col-md-3 offset-md-1"><%= @end_user.id%></div>
  </div>

  <div class="form-group row">
    <div class="col-6 col-md-2 offset-md-4">ユーザー画像</div>
    <div class="col-6 col-md-5 offset-md-1"><%= image_tag @end_user.get_profile_image(80,80) %></div>
  </div>

  <div class="form-group row">
    <div class="col-6 col-md-2 offset-md-4">ニックネーム</div>
    <div class="col-6 col-md-5 offset-md-1"><%= @end_user.nick_name %></div>
  </div>

  <div class="form-group row">
    <div class="col-6 col-md-2 offset-md-4">メールアドレス</div>
    <div class="col-6 col-md-5 offset-md-1 end-user-email"><%= @end_user.email %></div>
  </div>

  <div class="form-group row">
    <div class="col-6 col-md-2 offset-md-4">性別</div>
    <div class="col-6 col-md-5 offset-md-1"><%= @end_user.gender_i18n %></div>
  </div>

  <div class="form-group row">
    <div class="col-6 col-md-2 offset-md-4">年齢</div>
    <div class="col-6 col-md-5 offset-md-1"><%= @end_user.calc_age %></div>
  </div>

  <div class="form-group row">
    <div class="col-6 col-md-2 offset-md-4">職業</div>
    <div class="col-6 col-md-5 offset-md-1"><%= @end_user.occupation %></div>
  </div>

  <div class="form-group row">
    <div class="col-6 col-md-2 offset-md-4">ユーザーステータス</div>
    <% if @end_user.is_deleted == false %>
      <div class="col-3 text-success col-md-5 offset-md-1">有効</div>
    <% else %>
      <div class="col-3 text-secondary col-md-5 offset-md-1">退会</div>
    <% end %>
  </div>

  <div class="row">
    <div class="col-12 offset-2 col-md-5 offset-md-7">
      <%= link_to "編集する", edit_admin_end_user_path(@end_user.id), class: "btn btn-outline-success text-dark" %>
      <%= link_to '戻る', admin_end_users_path, class: "btn btn-outline-secondary text-dark offset-md-1" %>
    </div>
  </div>
</div>