config/routes.rb
Rails.application.routes.draw do

  devise_for :end_users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions',
  }

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions",
  }

  root to: 'public/homes#top'
  get '/about' => 'public/homes#about'
  get '/rakuten_books' => 'public/rakuten_books#search'
  get "/unsubscribe/end_users/:id" => "public/end_users#unsubscribe", as: 'unsubscribe'
  get 'chat/:id' => 'public/chats#show', as: 'chat'
  get "search" => "public/searches#search"
  patch "end_users/withdraw" => "public/end_users#withdraw"
  post "contacts/new" => "public/contacts#create"
  get "/thanks" => "public/contacts#thanks"

  scope module: :public do
    patch "/end_users/withdraw" => "end_users#withdraw"
    get 'searches/search_result'
    resources :end_users, only: [:edit, :update, :index, :show] do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
    resources :reviews, except: [:index] do
      resources :comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
      collection do
        get 'sort_new'
        get 'sort_rate'
      end
    end
    resources :chats, only: [:create]
    resources :notifications, only: [:index, :destroy]
    resources :contacts, only: [:new]
  end

  namespace :admin do
    resources :genres, only: [:index, :create, :destroy]
    resources :end_users, only: [:index, :show, :edit, :update]
    root to: "homes#top"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_end_user_info.html.erb
<div class="container">
  <div class="row mt-5">
    <h3 class="mx-auto">User's Info</h3>
    <table class="table table-striped">
      <tbody>
        <tr>
          <th><%= image_tag end_user.get_profile_image(100,100) %></th>
          <th></th>
        </tr>
        <tr>
          <th><%= end_user.nick_name %></th>
          <th></th>
        </tr>
        <tr>
          <th><%= end_user.gender_i18n %></th>
          <th></th>
        </tr>
        <tr>
          <th><%= end_user.calc_age %>歳</th>
          <th></th>
        </tr>
        <tr>
          <th><%= end_user.occupation %></th>
          <th></th>
        </tr>
        <tr>
          <th>フォロー</th>
          <th><%= link_to end_user.followings.count, end_user_followings_path(end_user) %></th>
        </tr>
        <tr>
          <th>フォロワー</th>
          <th><%= link_to end_user.followers.count, end_user_followers_path(end_user) %></th>
        </tr>
      </tbody>
    </table>
    <%= render 'public/end_users/relationship', end_user: end_user %>
  </div>
</div>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "") %> 件のエラーが発生しました。</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="background-color-header-footer p-3">
  <div class="mx-auto">
    <p class="text-center mt-2">
      © All right reserved by Culture Square supported by
      <img class="rakuten-image mt-3" src="https://webservice.rakuten.co.jp/img/developers_logo.svg">
    </p>
  </div>
  <% if end_user_signed_in? %>
    <div class="mx-auto">
      <p class="text-center">
        <%= link_to 'このサイトに関するお問い合わせはこちらから', new_contact_path, class: "text-dark btn btn-outline-warning" %>
      </p>
    </div>
  <% end %>
</div>

app/views/layouts/_genre_index.html.erb
<div class="card">
  <div class="card-header text-center">
    <strong>ジャンル</strong>
  </div>
  <div class="card-body text-center">
    <a href="#panel-0" class="nav-link" data-toggle="tab" onclick="changeGenrePanelAttribute(0)">
      <strong>
        <span class="text-blue">総合</span>
      </strong>
    </a>
    <% genres.each_with_index do |genre, index| %><!--each_with_indexを使うことにより、eachで回す回数をindexへ代入している。-->
      <a href="#panel-<%= genre.id %>" class="nav-link" data-toggle="tab" onclick="changeGenrePanelAttribute(<%=genre.id%>)">
        <strong>
          <span class="text-blue"><%= genre.name %></span>
        </strong>
      </a>
    <% end %>
  </div>
</div>

<!-- クリックされた時に発火させる。idとpanelを取得して'active'をつけ、クリックされていないところは'active'をremoveしている。 -->
<script>
function changeGenrePanelAttribute(genre_id)
{
  for (var i = 0;i <= <%=genres.maximum(:id)%>;i++) {//iの初期値を0、それ以降は全ジャンルのidを取り出している。
    var id = 'genre_panel_' + i;
    var panel_id = 'panel-' + i;
    var genre_panel = document.getElementById(id);//documentはhtml要素を取得、getElementByIdでその要素を取得している。
    var panel = document.getElementById(panel_id);
    if (panel != null && genre_panel != null) {
      panel.classList.remove('active');
      genre_panel.classList.remove('active');
    }
  }
  var id = 'genre_panel_' + genre_id;
  var panel_id = 'panel-' + genre_id;
  var genre_panel = document.getElementById(id);
  var panel = document.getElementById(panel_id);
  panel.classList.add('active');//ジャンル毎のレビューをactiveにしている
  genre_panel.classList.add('active');//ジャンルパネルをactiveにしている
}
</script>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light background-color-header-footer p-2 mb-5">
  <div class="col-2 col-md-1 offset-md-1">
    <%= link_to root_path, class: "navbar-brand" do %>
    <p class="logo"></p>
    <% end %>
  </div>
  <% if end_user_signed_in? %>
    <div class="header-search">
      <h5>Welcome to<br />
        <strong><%= current_end_user.nick_name %></strong>さん!
      </h5>
      <%= render 'layouts/search' %>
    </div>
  <% end %>
  <div class="col-10 col-md-10">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <% if end_user_signed_in? %>
          <h3 class="pr-5 pl-5">Welcome to<br />
            <strong><%= current_end_user.nick_name %></strong>さん!
          </h3>
          <li class="pr-3">
            <%= link_to 'Top', root_path, class: "btn btn-outline-secondary text-dark" %>
          </li>
          <li class="pr-3">
            <%= link_to 'About', about_path, class: "btn btn-outline-secondary text-dark" %>
          </li>
          <li class="pr-3">
            <%= link_to 'My page', end_user_path(current_end_user), data: { 'turbolinks': false }, class: "btn btn-outline-secondary text-dark" %>
          </li>
          <li class="pr-3">
            <%= link_to 'Users', end_users_path, class: "btn btn-outline-secondary text-dark" %>
          </li>
          <li class="pr-3">
            <% if unchecked_notifications.any? %>
              <%= link_to "Notice", notifications_path, class: "btn btn-outline-secondary bg-warning", style: "color: red;" %>
            <% else %>
              <%= link_to "Notice", notifications_path, class: "btn btn-outline-secondary text-dark" %>
            <% end %>
          </li>
          <li class="pr-3">
            <%= link_to 'Log out', destroy_end_user_session_path, method: :delete, class: "btn btn-outline-secondary text-dark" %>
          </li>
          <li><%= render 'layouts/search' %></li>
        <% elsif admin_signed_in? %>
          <li class="pr-3">
            <%= link_to 'EndUsers', admin_end_users_path, class: "text-dark btn btn-outline-secondary" %>
          </li>
          <li class="pr-3">
            <%= link_to 'Genres', admin_genres_path, class: "text-dark btn btn-outline-secondary" %>
          </li>
          <li>
            <%= link_to 'Log out', destroy_admin_session_path, method: :delete, class: "text-dark btn btn-outline-secondary" %>
          </li>
        <% else %>
          <li class="pr-3">
            <%= link_to " Top ", root_path, class: "text-dark btn btn-outline-secondary" %>
          </li>
          <li class="pr-3">
            <%= link_to "About", about_path, class: "text-dark btn btn-outline-secondary" %>
          </li>
          <li class="pr-3">
            <%= link_to "Sign up", new_end_user_registration_path, class: "text-dark btn btn-outline-secondary" %>
          </li>
          <li>
            <%= link_to "Log in", new_end_user_session_path,class: "text-dark btn btn-outline-secondary" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_rakuten_books_search.html.erb
<%= form_with url: rakuten_books_path, method: :get, local:true do |f| %>
  <%= f.text_field :keyword, autofocus: true, placeholder: "キーワード検索（書籍タイトル、著者）", class: "form-control", size: 90 %>
  <%= f.submit '検索', class: "btn btn-outline-primary text-dark mt-2", id: 'rakuten_seach' %>
<% end %>

app/views/layouts/_search.html.erb
<% if end_user_signed_in? %>
  <%= form_with url: search_path, local: true, method: :get do |f| %>
    <%= f.text_field :word, placeholder:"サイト内検索...", class:"form-control" %>
    <%= f.select :range, options_for_select([['User', 'EndUser'], ['Review'], ['Book']]) %>
    <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backward_match"], ["部分一致","partial_match"]]) %>
    <%= f.submit "検索", class: "btn btn-outline-primary text-dark btn-sm mt-2" %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title>CultureSquare</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all' %>

    <!--<script src="http://code.jquery.com/jquery.min.js"></script>-->

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel ="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">

  </head>

  <body id="vegas-body">
    <div id="sp-menu">
      <h2 class="text-center mt-5">MENU</h2>
      <ul class="p-4">
        <% if end_user_signed_in? %>
          <li><%= link_to 'Top', root_path %></li>
          <li><%= link_to 'About', about_path %></li>
          <li><%= link_to 'My Page', end_user_path(current_end_user), data: { 'turbolinks': false } %></li>
          <li><%= link_to 'Users', end_users_path %></li>
          <li><%= link_to "Notice", notifications_path %></li>
          <li><%= link_to 'Log out', destroy_end_user_session_path, method: :delete %></li>
        <% elsif admin_signed_in? %>
          <li>
            <%= link_to 'EndUsers', admin_end_users_path %>
          </li>
          <li>
            <%= link_to 'Genres', admin_genres_path %>
          </li>
          <li>
            <%= link_to 'Log out', destroy_admin_session_path, method: :delete %>
          </li>
        <% else %>
          <li><%= link_to 'Top', root_path %></li>
          <li><%= link_to 'About', about_path %></li>
          <li><%= link_to "Sign up", new_end_user_registration_path %></li>
          <li><%= link_to 'Log in', new_end_user_session_path %></li>
        <% end %>
      </ul>
    </div>

    <div id="hm-icon">
      <a class="menu-trigger" href="#">
        <span></span>
        <span></span>
        <span></span>
      </a>
    </div>

    <header>
      <%= render 'layouts/header' %>
    </header>

    <main>
      <!--バリデーションチェック用-->
      <div class="flash-message fadeout">
        <% flash.each do |key, value| %>
          <%= content_tag(:div, value, class: key) %>
        <% end %>
      </div>
      <%= yield %>
    </main>


    <span id="back">
      <%= link_to (image_tag('arrow.jpg')), '#' %>
    </span>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.7.1/chart.min.js"
      integrity="sha512-QSkVNOCYLtj73J4hbmVoOV6KVZuMluZlioC+trLpewV8qMjsWqlIQvkn1KGX2StWvPMdWGBqim1xlC8krl1EKQ=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer">
    </script>
  </body>
  <footer>
    <%= render 'layouts/footer' %>
  </footer>

</html>